name: Publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install --upgrade pyyaml
      - name: Gen Build Command
        run: |
          python ./conda.recipes/getChannels.py > build_command.txt
      - name: publish-to-conda
        uses: rfun/conda-package-publish-action@master
        with:
          subDir: "conda.recipes"
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: "Tethys App Warehouse: Build complete for whats_app"
          # Literal body:
          body: "
        Your Tethys App has been successfully built and is now available on the Tethys App Warehouse.
        This is an auto-generated email and this email is not monitored for replies. Please send any queries to rohitkh@byu.edu
        "
          to: rohitkhattar11@gmail.com
          from: Tethys App Warehouse